version : "3.8"

services:
   frontend:
      build : /root/docker/frontends
      container_name: frontend
      ports :
      - "80:80"
      network_mode: bridge

    backend:
      build :/root/docker/backend  
      container_name: backend
      ports: 
       - "8080:8080"
      depeonds_on :
      - frontend
      network_mode : bridge


