FROM ubuntu:24.04
RUN apt-get update
RUN apt-get install -y nginx zip curl
RUN  echo "deamon off;"  >>/etc/nginx/nginx.conf
RUN  curl - O /var/www/html/master.zip -L https://github.com/gabrielecirulli/2048.git 
RUn  cd /var/www/html/ && unzip master.zip && mv 2048-master/*. && rm - rf 2048-master master.zip 

EXPOSE 80

CMD ["/usr/sbin/nginx","-c","/etc/nginx/nginx.conf"]